# trigger docker build
version: 2.0

jobs:
  hook:
    docker:
      - image: circleci/ruby:2.4
    steps:
      - run:
          name: send hook
          command: curl -XPOST "${DOCKER_CLOUD_BASE_BUILD_HOOK}"
workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "0 3 * * 0"
          filters:
            branches:
              only:
                - master
    jobs:
      - hook
