# trigger docker build
version: 2.0

jobs:
  hook:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: pip
          command: pip install --user feedparser       
      - run:
          name: send hook on update
          command: python checkupdate.py -t amzn2 || curl -XPOST "${DOCKER_CLOUD_BASE_BUILD_HOOK}"
workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "0 3 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - hook
